language: java

sudo: false

services:
- docker

env:
- DOCKER_IMAGE_NAME=tangocs/rest-server REGISTRY_USER=ingvord

#skip mvn install
install: /bin/true

before_script:
  - docker-compose up -d
  #TODO wait-for-it
  - sleep 30
  - docker ps

script:
  - mvn -B verify -Ptravis,test-suite -Dcustom.build.name=$TRAVIS_BRANCH

after_success:
  - git fetch --unshallow
  - mvn sonar:sonar -Ptravis
  - docker build --pull --cache-from "${DOCKER_IMAGE_NAME}:latest" --tag "$DOCKER_IMAGE_NAME" --build-arg REST_SERVER_VERSION=$TRAVIS_BRANCH .

jdk: 
  - openjdk8
  
addons:
  sonarcloud:
    organization: "ingvord-github"
    token:
      secure: $SONAR_TOKEN  

before_deploy:
- docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASS"
- docker tag "$DOCKER_IMAGE_NAME" "${DOCKER_IMAGE_NAME}:${TRAVIS_BRANCH}"

deploy:
  - provider: script
    script: docker push "${DOCKER_IMAGE_NAME}:${TRAVIS_BRANCH}"
  - provider: releases
    api_key: $GITHUB_OAUTH_TOKEN
    file:
      - "target/$TRAVIS_TAG.jar"
      - "target/$TRAVIS_TAG.zip"
    skip_cleanup: true
    on:
      tags: true

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
