language: java

sudo: false

services:
- docker

#before_install:
#- sudo rm /usr/local/bin/docker-compose
#- curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
#- chmod +x docker-compose
#- sudo mv docker-compose /usr/local/bin
#- docker-compose --version

#skip mvn install
install: /bin/true

before_script:
  - docker-compose up -d
  #TODO wait-for-it
  - sleep 30
  - docker ps

script:
  - mvn -B verify -Ptravis,test-suite -Dcustom.build.name=$TRAVIS_BRANCH

after_success:  
  - mvn sonar:sonar -Ptravis

jdk: 
  - openjdk8
  
addons:
  sonarcloud:
    organization: "ingvord-github"
    token:
      secure: $SONAR_TOKEN  

deploy:
  - provider: releases
    api_key: $GITHUB_OAUTH_TOKEN
    file:
      - "target/$TRAVIS_TAG.jar"
      - "target/$TRAVIS_TAG.zip"
    skip_cleanup: true
    on:
      tags: true

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
