language: java

sudo: false

script:
  - mvn clean package -Ptravis
  - java -DTANGO_HOST=localhost:10000 -jar target/mtangorest.server-rc4-2.5-SNAPSHOT.jar -nodb -dlist test/rest/0 &
  - sleep 10
  - curl -u "tango-cs:tango" http://localhost:10001/tango/rest/rc4 | grep "\"hosts\":\"http://localhost:10001/tango/rest/rc4/hosts\""
  - killall java

after_success:  
  - mvn sonar:sonar -Ptravis

jdk: 
  - openjdk8
  
addons:
  sonarcloud:
    organization: "ingvord-github"
    token:
      secure: $SONAR_TOKEN  

deploy:
  - provider: releases
    api_key: $GITHUB_OAUTH_TOKEN
    file:
      - "target/mtangorest.server-$TRAVIS_TAG.jar"
      - "target/mtangorest.server-$TRAVIS_TAG.zip"
    skip_cleanup: true
    on:
      tags: true

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
