language: java

sudo: false

services:
- docker

#skip mvn install
install: /bin/true

before_script:
  - docker-compose up -d
  #TODO wait-for-it
  - sleep 30
  - docker ps

script:
  - mvn -B verify -Ptravis,test-suite -Dcustom.build.name=$TRAVIS_BRANCH

after_success:
  - git fetch --unshallow
  - mvn sonar:sonar -Ptravis

jdk: 
  - openjdk8
  
addons:
  sonarcloud:
    organization: "ingvord-github"
    token:
      secure: $SONAR_TOKEN  

deploy:
  - provider: releases
    api_key: $GITHUB_OAUTH_TOKEN
    file:
      - "target/$TRAVIS_TAG.jar"
      - "target/$TRAVIS_TAG.zip"
    skip_cleanup: true
    on:
      tags: true

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
