# This is a sample build configuration for Maven.
# Check our guides at https://confluence.atlassian.com/x/VYk8Lw for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: maven:3.3.3

pipelines:
  default:
    - step:
        script: # Modify the commands below to build your repository.          
#          - apt-get install git
#          - git clone https://github.com/tango-controls/rest-api.git           
          - mvn clean package
          - java -jar target/mtangorest.server-rc4-0.1-SNAPSHOT.jar development &
#          - cd rest-api
#          - mvn compile
          - uname -a